#!/usr/bin/env bash

capacity="$(cat /sys/class/power_supply/BAT0/capacity)" || exit 1
status="$(cat /sys/class/power_supply/BAT0/status)" || exit 1

if [ ! "$status" = "Discharging" ]; then
	label=""
else
	label=""
fi

echo "$label $capacity%"

# udevadm monitor -s=power_supply
