[accounts."ryan@freumh.org"]
default = true
email = "ryan@freumh.org"
display-name = "Ryan Gibb"
backend = "maildir"
maildir.root-dir = "~/mail/ryan@freumh.org"
folder.alias.inbox = "~/mail/ryan@freumh.org/Inbox"
folder.alias.sent = "Sent"
message.send.backend = "sendmail"
sendmail.cmd = "msmtpq --read-envelope-from --read-recipients"
downloads-dir = "~/downloads"

[accounts."misc@freumh.org"]
email = "misc@freumh.org"
display-name = "Ryan Gibb"
backend = "maildir"
maildir.root-dir = "~/mail/misc@freumh.org"
folder.alias.inbox = "~/mail/misc@freumh.org/Inbox"
folder.alias.sent = "Sent"
message.send.backend = "sendmail"
sendmail.cmd = "msmtpq --read-envelope-from --read-recipients"
downloads-dir = "~/downloads"

[accounts."ryan.gibb@cl.cam.ac.uk"]
email = "ryan.gibb@cl.cam.ac.uk"
display-name = "Ryan Gibb"
backend = "maildir"
maildir.root-dir = "~/mail/ryan.gibb@cl.cam.ac.uk"
folder.alias.inbox = "~/mail/ryan.gibb@cl.cam.ac.uk/Inbox"
folder.alias.sent = "Sent"
message.send.backend = "sendmail"
sendmail.cmd = "msmtpq --read-envelope-from --read-recipients"
downloads-dir = "~/downloads"

[accounts."ryangibb321@gmail.com"]
email = "ryangibb321@gmail.com"
display-name = "Ryan Gibb"
backend = "maildir"
maildir.root-dir = "~/mail/ryangibb321@gmail.com"
folder.alias.inbox = "~/mail/ryangibb321@gmail.com/Inbox"
folder.alias.sent = "Sent"
message.send.backend = "sendmail"
sendmail.cmd = "msmtpq --read-envelope-from --read-recipients"
downloads-dir = "~/downloads"
