#!/usr/bin/env bash

INTERFACES=`nmcli -t -f DEVICE,TYPE,STATE,CONNECTION device status`

SSID=`echo "$INTERFACES" | awk -F : '/wifi:connected/ {print $4}'`

# if it exists, display wireless SSID with SIGNAL strenght
if [ ! -z "$SSID" ]; then
	SIGNAL=`nmcli -t -f IN-USE,SSID,SIGNAL dev wifi list | awk -F : "/^\*:$SSID/ {print \\$3}"`
	echo " $SIGNAL% $SSID"
# otherwise, if ethernet connection exists display that
elif [ ! -z "$(echo $INTERFACES | awk -F : '/ethernet:connected/ {print $4}')" ]; then
	echo " "
# if there's no connection, display unlink
else
	echo " "
fi

