#!/usr/bin/env bash

# Get the first interface beinging with 'wl'
INTERFACE=$(ip a | grep '^[0-9]: wl' | awk '{print $2}' | grep -Eo "[A-Za-z0-9]*" | head -n 1)

# if the machine has no wireless connection don't display
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "🗙"
    exit
fi

WIRELESS_INFO="$(cat /proc/net/wireless)"

SIGNAL="$(echo "$WIRELESS_INFO" | grep "$INTERFACE" | awk '{print $4}' | grep -Eoe '-[0-9]{2}')"
QUALITY="$(echo "$SIGNAL" | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')"

SSID="$(iwgetid | head -n 1 | sed 's/[^:]*:"//; s/"//')"

echo " $QUALITY% $SSID"
